version: "3.8"

services:
  caddy:
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - "data:/data"
    networks:
      gitlab_net:
        aliases:
          - caddy.caddy

networks:
  gitlab_net:
    external: true
    name: gitlab_net

volumes:
  data:
    external: true
    name: "caddy.data"

configs:
  caddyfile:
    external: true
    name: "caddy.caddyfile"
