version: '3'
services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:13.9.4-ce.0'
    restart: unless-stopped
    ports:
      - '10.0.0.4:22:22'
    volumes:
      - 'conf:/etc/gitlab/'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'

networks:
  default:
    external:
      name: 'gitlab'

volumes:
  conf:
    external:
      name: 'gitlab_gitlab_conf'
  logs:
    external:
      name: 'gitlab_gitlab_logs'
  data:
    external:
      name: 'gitlab_gitlab_data'
