# VERDACCIO_PUBLIC_URL
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

middlewares:
  gitlab-oauth:
    enabled: true
  audit:
    enabled: true

auth:
  gitlab-oauth:
    group: $EXT_GITLAB_GROUP
    client-id: $EXT_GITLAB_OAUTH_CLIENT_ID
    client-secret: $EXT_GITLAB_OAUTH_CLIENT_SECRET
    gitlab-host: $EXT_GITLAB_HOST

web:
  enable: true
  title: GeekTR NPM
  scope: "@gtr"
  logo: /logo.svg
  darkMode: true

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 30d
      notBefore: 1

uplinks:
  npmjs:
    url: http://registry.npm.taobao.org/
    maxage: 30d

packages:
  "@gtr/*":
    access: $all
    publish: $EXT_GITLAB_GROUP
  "@gtr-pri/*":
    access: $EXT_GITLAB_GROUP
    publish: $EXT_GITLAB_GROUP
  "**":
    access: $all
    publish: $EXT_GITLAB_GROUP
    proxy: npmjs

http_proxy: http://proxy.geektr.co:3128
https_proxy: http://proxy.geektr.co:3128
no_proxy: localhost,127.0.0.1

logs:
  - { type: stdout, format: pretty, level: http }
